### ISSUE TITLE
Picture of Optima 7 is broken

### ISSUE THREAD

**Issue by zerocoolminja** [Zero3nna/untestedprototype#1]
Please update picture of Optima 7.

**Comment by zero3nna** [comment]
This picture was from another web source which seems to be offline currently. I will check this back later and hopefully can store the image local.

**Comment by zerocoolminja** [comment]
Ok, thank you.

**Comment by zero3nna** [comment]
If someone is using a Optima 7 and would like to contribute a image of the raw board, please send me an PM.

**Comment by zero3nna** [comment]
Images are back
