### ISSUE TITLE
S.Bus protocol

### ISSUE THREAD

**Issue by tloki** [Zero3nna/untestedprototype#2]
It would be nice to support an S.Bus protocol (which is a bit "faster") than PPM.

Is this possible? Also, could it be supported, even in theory?

**Comment by sdriessens** [comment]
It is possible to implement S.Bus on the slave, but it won’t offer much benefit. The master only sends updated frames at a fixed interval around 50 Hz.

Scott
________________________________

**Comment by tloki** [comment]
Well, yes that would be one huge waste of time, totally forgot about it!

EDIT: Does this also reflect in case of a newer Aurora 9X (as one is marketed as having 7ms frame time, or about 140Hz), or by master you mean a "master component" of the receiver?

**Comment by julioghigi** [comment]
By master his mean a master component, there are two microcontrolers on the receiver, the master and the slave, we only modify the slave.
