### ISSUE TITLE
Optima 9 Slave mega168

### ISSUE THREAD

**Issue by julioghigi** [Zero3nna/untestedprototype#3]
Hi! 
Can you confirm to me that the slave mega is the one if thw "2" next to it? 
And I just wanna know if is possible to generate a Sbus signal istead of PPM, cause if yea I will try to code.
Thanks!
![optima9](https://user-images.githubusercontent.com/41697757/49960699-efe5eb80-fef7-11e8-8b5d-8f68e5d2a3cc.jpeg)

**Comment by julioghigi** [comment]
Yes, this is the correct ATmega, and I got this workin, now I am codding the Sbus and will bring it soon

**Comment by tloki** [comment]
What is the point of s.bus telemetry is the master AVR is sending data @ 50Hz? Does s.bus assume something like ability for native Betaflight telemetry?

**Comment by julioghigi** [comment]
Yes I saw on the other issue the problem with refresh time of the master, I dont think Sbus can do telemetry, this is capable only with Smartport on the FrSky and something like this.

**Comment by julioghigi** [comment]
I will open another issue to talk more about Sbus
