### ISSUE TITLE
Pictures for Programming connection are broken

### ISSUE THREAD

**Issue by ciafe** [Zero3nna/untestedprototype#5]
Hello, 
I'm interested in the Optima 7 firmware update to get the PPM output, but the images are broken and I can 't get the information on how to solder the programming connector.

Would it be possible to add them again or write the information? thanks a lot!

**Comment by tloki** [comment]
![hitec](https://user-images.githubusercontent.com/26622655/52737898-be5bd000-2fcd-11e9-945b-a76be8a0ce5a.jpeg)
![img_0592](https://user-images.githubusercontent.com/26622655/52737908-c451b100-2fcd-11e9-900a-a5720b914cef.JPG)
I was able to find these images on web archive. I have personally flashed this firmware on 3 of my Optima7, but unsoldered all the wires... Hope this helps.

**Comment by zero3nna** [comment]
i will update the readme with fixed images
tloki‘s images are correct 👍

**Comment by ciafe** [comment]
Thanks a lot, it helps a lot!! :)

Let's give a second life to the Hitec receivers!

Very interesting SW hack @zero3nna , I will start with your SW, but my plan is to add Failsafe features, and with some additional HW, add also SBUS capabilities (there are severla libraries arround there). Let's see if I have the time to do it...

**Comment by ciafe** [comment]
Hello @zero3nna,

I'm working on the SBUS version, but I have a doubt with the Hitec protocol. Could you detail me which is the format of the data we get from the other microcontroller in the serial line?

My question is mainly in this line of code:
_inputs[i] = ((uint16_t)(buffer[2*i] << 8) | (uint16_t)buffer[2*i+1]) - PPM_PRE_PULSE;_

Where you are substracting the PPM_PRE_PULSE (after creating the 16b data) which is in counter ticks, not un microseconds. Does it means that the other uC send the information in that format?

I'm migrating the code to be compiled with Arduino miniCore, and the delays now are in us, not in counter ticks. 

Thanks for you support!

By the way, I'm already using my Optima7 receiver in PPM mode perfectly! Thanks for the project.

**Comment by zero3nna** [comment]
images are back
